library(stringi)
library(tm)
library(slam)
library(tidyr)
library(dplyr)
library(quanteda)
set.seed(1988)
twitter <- readLines('en_US.twitter.txt')
blogs <- readLines('en_US.blogs.txt')
news <- readLines('en_US.news.txt')
smallTwitter <- sample(twitter, length(twitter)*.75)
smallBlogs <- sample(blogs, length(blogs)*.75)
smallNews <- sample(news, length(news)*.75)
remove(twitter)
remove(blogs)
remove(news)
smallCombo <- c(smallBlogs, smallTwitter, smallNews)
remove(smallTwitter)
remove(smallBlogs)
remove(smallNews)
badWords <- readLines("./badwords.txt")
badWords <- paste("\\b",badWords,"\\b", sep="")
Encoding(smallCombo) <- "latin1"
smallCombo <- iconv(smallCombo, "latin1", "ASCII", sub="")

df1 <- rbind(df1.1, df1.2, df1.3, df1.4, df1.5, df1.6)
df1 <- df1 %>% select(unigram, freq)
df1 <- df1 %>% group_by(unigram) %>% summarise(freq = sum(freq))
df1 <- df1 %>% dplyr::arrange(desc(freq))
df1 <- df1 %>% mutate(prob = freq/sum(freq))

df2 <- rbind(df2.1, df2.2, df2.3, df2.4, df2.5, df2.6)
df2 <- df2 %>% group_by(bigram) %>% summarise(freq = sum(freq))
df2 <- df2 %>% dplyr::arrange(desc(freq))
df2$bigram <- as.character(df2$bigram)
df2$end <- df2$bigram
df2 <- df2 %>% separate(col = end, into = c('start', 'end'), sep = "_")
df2 <- df2 %>% group_by(start) %>% mutate(total = sum(freq))
df2 <- df2 %>% mutate(prob = freq/total)
df2 <- df2 %>% select(start, end, freq, total, prob)

df3 <- rbind(df3.1, df3.2, df3.3, df3.4, df3.5, df3.6)
df3 <- df3 %>% group_by(trigram) %>% summarise(freq = sum(freq))
df3 <- df3 %>% dplyr::arrange(desc(freq))
df3$trigram <- as.character(df3$trigram)
df3$end <- df3$trigram
df3 <- df3 %>% separate(col = end, into = c('first', 'second', 'end'), sep = "_")
df3 <- df3 %>% unite(start, first, second, sep = " ")
df3 <- df3 %>% group_by(start) %>% mutate(total = sum(freq))
df3 <- df3 %>% mutate(prob = freq/total)
df3 <- df3 %>% select(start, end, freq, total, prob)

df4 <- rbind(df4.1, df4.2, df4.3, df4.4, df4.5, df4.6)
df4 <- df4 %>% group_by(quadgram) %>% summarise(freq = sum(freq))
df4 <- df4 %>% dplyr::arrange(desc(freq))
df4$quadgram <- as.character(df4$quadgram)
df4$end <- df4$quadgram
df4 <- df4 %>% separate(col = end, into = c('first', 'second', 'third', 'end'), sep = "_")
df4 <- df4 %>% unite(start, first, second, third, sep = " ")
df4 <- df4 %>% group_by(start) %>% mutate(total = sum(freq))
df4 <- df4 %>% mutate(prob = freq/total)
df4 <- df4 %>% select(start, end, freq, total, prob)

# df1 <- df1[order(df1$Freq, decreasing = TRUE),]
# df1 <- df1 %>% mutate(prob = Freq/sum(Freq))
# saveRDS(df1, "unigrams.RDS")
# remove(df1)
# 
# df2$bigram <- as.character(df2$bigram)
# df2$end <- df2$bigram
# df2 <- df2 %>% separate(col = end, into = c('start', 'end'), sep = "_")
# df2 <- df2 %>% group_by(start) %>% mutate(total = sum(freq))
# df2 <- df2 %>% mutate(prob = freq/total)
# saveRDS(df2, "bigrams.RDS")
# remove(df2)
# 
# df3$trigrams <- as.character(df3$trigrams)
# df3$end <- df3$trigrams
# df3 <- df3 %>% separate(col = end, into = c('first', 'second', 'third'), sep = "\\s")
# df3 <- df3 %>% unite(start, first, second, sep = " ")
# df3 <- df3 %>% group_by(start) %>% mutate(total = sum(freq))
# df3 <- df3 %>% mutate(prob = freq/total)
# saveRDS(df3, "trigrams.RDS")
# remove(df3)
# 
# df4 <- df4[order(df4$Freq, decreasing = TRUE),]
# df4$quadgrams <- as.character(df4$quadgrams)
# df4$end <- df4$quadgrams
# df4 <- df4 %>% separate(col = end, into = c('first', 'second', 'third', 'end'), sep = "\\s")
# df4 <- df4 %>% unite(start, first, second, third, sep = " ")
# df4 <- df4 %>% group_by(start) %>% mutate(total = sum(freq))
# df4 <- df4 %>% mutate(prob = freq/total)
# saveRDS(df4, "quadgrams.RDS")
# remove(df4)